trccmd: better validity checks done now

diff --git a/kernel_debug/tracing/ftrace/trccmd b/kernel_debug/tracing/ftrace/trccmd
--- a/kernel_debug/tracing/ftrace/trccmd
+++ b/kernel_debug/tracing/ftrace/trccmd
@@ -7,9 +7,8 @@ name=$(basename $0)
 TRC_FILE=/tmp/trc.txt
 TRC_FILE_TRCOMP=/tmp/trc_trcomp.txt
 
-
 ## "main" here
-[ `id -u` -ne 0 ] && {
+[ $(id -u) -ne 0 ] && {
  echo "${name}: Need to be root."
  exit 1
 }
@@ -18,17 +17,35 @@ mount | grep debugfs > /dev/null 2>&1 || {
  echo "${name}: debugfs not mounted? Aborting..."
  exit 1
 }
-[ ! -d /sys/kernel/debug/tracing ] && {
- echo "${name}: /sys/kernel/debug/tracing not mounted? Aborting..."
+#[ ! -d /sys/kernel/debug/tracing ] && {
+# echo "${name}: /sys/kernel/debug/tracing not mounted? Aborting..."
+# exit 2
+#}
+
+mount | grep debugfs > /dev/null 2>&1 || {
+ echo "${name}: debugfs not mounted? Aborting..."
+ exit 1
+}
+mount |grep -q -w debugfs || {
+ echo "${name}: debugfs filesystem not mounted? Aborting..."
  exit 2
 }
- which trace-cmd >/dev/null 2>&1 || {
+TRCMNT=$(mount |grep -w debugfs |awk '{print $3}')
+export TRCMNT=${TRCMNT}/tracing
+[ ! -d ${TRCMNT} ] && {
+ echo "${name}: ${TRCMNT} not mounted as debugfs? Aborting..."
+ exit 2
+}
+echo " [OK] (ftrace loc: ${TRCMNT})"
+
+which trace-cmd >/dev/null 2>&1 || {
   echo "${name}: trace-cmd not installed (or not in PATH)?"
   exit 1
  }
-echo " [OK]"
+echo "trace-cmd [OK]"
 
 [ $# -lt 1 ] && {
+ echo
  echo "Usage: ${name} program-to-ftrace-via-trace-cmd
  Eg. sudo ./${name} ps -LA
  [NOTE: this will perform an Exclusive ftrace of the provided app (ps in this eg)]"
@@ -42,7 +59,7 @@ trace-cmd record -p function_graph -F "$@" || {
 }
 
 echo "[+] Reporting now (ftrace) ..."
-echo "    Note: report done in latency format, leaving out interrupt contexts"
+echo "    Note: report done in latency format, *leaving out* interrupt contexts"
 trace-cmd report -I -S -l > ${TRC_FILE} || {
   echo "${name}: 'trace-cmd report' failed, aborting ..."
   exit 5
@@ -51,8 +68,8 @@ echo "[+] Done, report: ${TRC_FILE}"
 ls -lh ${TRC_FILE}
 
 # For LTTng TraceCompass GUI: record with -R     << not working w/ tracecompass?? >>
-echo "[+] Reporting now (for TraceCompass with -R) ..."
-echo "    Note: report done in latency format, leaving out interrupt contexts"
+echo "[+] Reporting now (for TraceCompass with -R;   YMMV, of course) ..."
+echo "    Note: report done in latency format, *leaving out* interrupt contexts"
 trace-cmd report -I -S -l -R > ${TRC_FILE_TRCOMP} || {
   echo "${name}: 'trace-cmd report' failed, aborting ..."
   exit 5
