Add config switches; add info on using with Trace Compass GUI

diff --git a/kernel_debug/tracing/ftrace/trccmd b/kernel_debug/tracing/ftrace/trccmd
--- a/kernel_debug/tracing/ftrace/trccmd
+++ b/kernel_debug/tracing/ftrace/trccmd
@@ -4,9 +4,12 @@
 #
 # Kaiwan NB, kaiwanTECH
 name=$(basename $0)
+
+#--- Configs
 TRC_FILE=/tmp/trc.txt
-WANT_TRCOMP_REP=0   # set to 1 to get the 'Trace Compass' format report file; YMMV :-p
-TRC_FILE_TRCOMP=/tmp/trc_trcomp.txt  # for Trace Compass
+WANT_RAW_FMT=1   # set to 1 to get the 'Trace Compass' format report file; YMMV :-p
+TRC_FILE_RAW=/tmp/trc_raw.txt  # for Trace Compass
+DONT_REPORT_IRQCTX=1  # filter out all interrupt context funcs from the final report
 
 ## "main" here
 [ $(id -u) -ne 0 ] && {
@@ -41,32 +44,59 @@ echo "trace-cmd [OK]"
  exit 3
 }
 
-echo "[+] Recording now ..."
-trace-cmd record -p function_graph -F "$@" || {
+TRC_FILE_BINARY=$(basename $1)_trc.dat
+#echo "TRC_FILE_BINARY = ${TRC_FILE_BINARY}"
+echo "[+] Recording now ...(binary ftrace file is ${TRC_FILE_BINARY})"
+trace-cmd record -p function_graph -o "${TRC_FILE_BINARY}" -F "$@" || {
   echo "${name}: 'trace-cmd record' failed, aborting ..."
   exit 4
 }
-
-echo "[+] Reporting now (ftrace) ..."
-echo "    Note: report done in latency format, *leaving out* interrupt contexts"
-trace-cmd report -i ./trace.dat -I -S -l > ${TRC_FILE} || {
-  echo "${name}: 'trace-cmd report' failed, aborting ..."
+ls ${TRC_FILE_BINARY} >/dev/null || {
+  echo "${name}: 'trace-cmd record' failed, no binary trace file, aborting ..."
   exit 5
+}
+
+echo "[+] Generating the trace-cmd report now ..."
+echo -n "    Note: report done in latency format"
+if [ ${DONT_REPORT_IRQCTX} -eq 1 ] ; then
+  echo ", *leaving out* interrupt contexts"
+  trace-cmd report -i "${TRC_FILE_BINARY}" -I -S -l > ${TRC_FILE}
+else
+  trace-cmd report -i "${TRC_FILE_BINARY}" -l > ${TRC_FILE}
+fi
+[ $? -ne 0 ] && {
+    echo "${name}: 'trace-cmd report' failed, aborting ..."
+    exit 6
 }
 echo "[+] Done, report: ${TRC_FILE}"
 ls -lh ${TRC_FILE}
 
-[ ${WANT_TRCOMP_REP} -eq 1 ] && {
-# For LTTng TraceCompass GUI: record with -R     << not working w/ tracecompass?? >>
-echo "[+] Reporting now (for TraceCompass with -R;   YMMV, of course) ..."
-echo "    Note: report done in latency format, *leaving out* interrupt contexts"
-#trace-cmd report -i ./trace.dat -I -S -l -R > ${TRC_FILE_TRCOMP} || {
-trace-cmd report -i ./trace.dat -R > ${TRC_FILE_TRCOMP} || {
-  echo "${name}: 'trace-cmd report' failed, aborting ..."
-  exit 5
-}
-echo "[+] Done, report: ${TRC_FILE_TRCOMP}"
-ls -lh ${TRC_FILE_TRCOMP}
+echo "
+NOTE-
+The binary data file generated by trace-cmd, here [${TRC_FILE_BINARY}]:
+    $(ls -lh ${TRC_FILE_BINARY})
+can be imported into the Trace Compass GUI and better visualized.
+Details here: using_tracecompass_gui_with_trccmd.txt
+(online: )
+"
+
+[ 0 -eq 1 ] && {
+[ ${WANT_RAW_FMT} -eq 1 ] && {
+ # For LTTng TraceCompass GUI: record with -R     << not working w/ tracecompass?? >>
+ echo "[+] Reporting now (for TraceCompass with -R (raw fmt);   YMMV, of course) ..."
+ if [ ${DONT_REPORT_IRQCTX} -eq 1 ] ; then
+  echo "    Note: report done in latency format, *leaving out* interrupt contexts"
+  trace-cmd report -i ./trace.dat -R > ${TRC_FILE_RAW}
+ else
+  trace-cmd report -i ./trace.dat -I -S -l -R > ${TRC_FILE_RAW}
+ fi
+ [ $? -ne 0 ] && {
+   echo "${name}: 'trace-cmd -R (raw) report' failed, aborting ..."
+   exit 5
+ }
+ echo "[+] Done, report: ${TRC_FILE_RAW}"
+ ls -lh ${TRC_FILE_RAW}
 } || echo "[Skipping (iffy) Trace Compass report file...]"
+}
 
 exit 0
