test for function_graph plugin; comments

diff --git a/kernel_debug/tracing/ftrace/trccmd b/kernel_debug/tracing/ftrace/trccmd
--- a/kernel_debug/tracing/ftrace/trccmd
+++ b/kernel_debug/tracing/ftrace/trccmd
@@ -1,8 +1,18 @@
 #!/bin/bash
 # trccmd
-# A simple wrapper over the useful trace-cmd front-end to ftrace
 #
-# Kaiwan NB, kaiwanTECH
+# A simple wrapper over the useful trace-cmd front-end to ftrace.
+# It uses the function_graph plugin.. records the session, generates the
+# binary <cmd>_trc.dat file as well as a human-readable 'report' file,
+# typically under /tmp/trc.txt.
+# 
+# As an additional feature, the binary data file generated by trace-cmd(1),
+# can be imported into the Trace Compass GUI and better visualized.
+# Details here: using_tracecompass_gui_with_trccmd.txt
+# (online: https://github.com/kaiwan/L5_debug_trg/blob/master/kernel_debug/tracing/ftrace/using_tracecompass_gui_with_trccmd.txt)
+#
+# (c) Kaiwan N Billimoria, kaiwanTECH
+# License: MIT
 name=$(basename "$0")
 
 #--- Configs
@@ -13,7 +23,7 @@ usage()
 {
    echo "Usage: ${name} [program-to-ftrace-via-trace-cmd]
  Eg. sudo ./${name} ps -LA
- NOTE: this will perform an _exclusive_ ftrace of the provided app (ps in this eg)
+ NOTE: this will perform an _exclusive_ ftrace of the provided app (ps in the above eg).
 If no program is provided as an argument, we shall trace-cmd(1) whatever's running."
 }
 
@@ -45,18 +55,27 @@ export TRCMNT=${TRCMNT}/tracing
 }
 echo " [OK] (ftrace loc: ${TRCMNT})"
 
+echo -n "[+] Checking for trace-cmd with function_graph plugin support ..."
 which trace-cmd >/dev/null 2>&1 || {
   echo "${name}: trace-cmd not installed (or not in PATH)?"
   exit 1
- }
-echo "trace-cmd [OK]"
+}
+# test for the 'function_graph' plugin support
+trace-cmd record -p function_graph -l kmem_cache_alloc -F ls / >/dev/null 2>&1 || {
+  echo "${name}: trace-cmd didn't work with the function-graph plugin, aborting..."
+  exit 2
+}
+rm -f trace.dat 2>/dev/null
+echo " [OK]"
 
 TRC_FILE_BINARY=trc.dat
 [ $# -ge 1 ] && TRC_FILE_BINARY=$(basename "$1")_trc.dat
 #echo "TRC_FILE_BINARY = ${TRC_FILE_BINARY}"
 echo "[+] Recording now ...(binary ftrace file is ${TRC_FILE_BINARY})"
 if [ $# -ge 1 ] ; then
-  trace-cmd record -p function_graph -o "${TRC_FILE_BINARY}" -F "$@"
+  trace-cmd record -p function_graph -o "${TRC_FILE_BINARY}" -c -F "$@"
+   # -F: trace only this executable
+   # -c: ...along with it's children, if any
 else
   trace-cmd record -p function_graph -o "${TRC_FILE_BINARY}"
 fi
@@ -90,6 +109,6 @@ The binary data file generated by trace-cmd, here [${TRC_FILE_BINARY}]:
     $(ls -lh "${TRC_FILE_BINARY}")
 can be imported into the Trace Compass GUI and better visualized.
 Details here: using_tracecompass_gui_with_trccmd.txt
-(online: )
+(online: https://github.com/kaiwan/L5_debug_trg/blob/master/kernel_debug/tracing/ftrace/using_tracecompass_gui_with_trccmd.txt)
 "
 exit 0
